name: loadtesting
namespace: jx-staging
image:
  name: "gcr.io/marionete-dev/mnist-loadtesting:latest"
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "1Mi"
replicas: "3"
env:
  HOST: "ambassor.gateway.3.130.155.243.nip.io"
  PORT: "80"
  NAMESPACE: jx-staging
  DEPLOYMENT: manticore

